services:
  v:
    image: khalyomede/vlang:latest-alpine
    entrypoint: v
    user: root
    working_dir: /root/app
    volumes:
      - .:/root/app
      - ./docker-data/v/.vmodules:/root/.vmodules
    ports:
      - "80:80"
